### PR TITLE
Portuguese_pt language file update

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Changed to UTF8
Added missing strings, according current english.inc

### CODE REVIEW

**Comment by michield** [comment]
Thanks!

**Comment by pedro-mendonca** [comment]
You're welcome.
I'm starting to understand how phplist is translated, I'm still a bit confused, but as far as I see there are lan-texts, lan-help, lan-info, and phplist.po. I'll do next the help and info. Ain't there redundancy in pagetitles.php and strings in phplist.po?
Thanks, I know this isn't probably the place to ask this but maybe you can help.

**Comment by michield** [comment]
Most is explained here: https://www.phplist.org/translation/#translate

**Comment by pedro-mendonca** [comment]
Thanks
:+1:

**Pull request merged**
